services:
  - type: web
    name: lms-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/lms-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SUPABASE_S3_ENDPOINT
        sync: false
      - key: SUPABASE_S3_REGION
        sync: false
      - key: SUPABASE_S3_ACCESS_KEY
        sync: false
      - key: SUPABASE_S3_SECRET_KEY
        sync: false
      - key: SUPABASE_S3_BUCKET
        sync: false
