spring:
  application:
    name: lms
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      connection-timeout: 30000  # 30 seconds
      idle-timeout: 600000      # 10 minutes
      max-lifetime: 1800000     # 30 minutes
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  cache:
    type: redis
  data:
    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: true
server:
  port: ${SERVER_PORT}

supabase:
  s3:
    endpoint: ${SUPABASE_S3_ENDPOINT}
    region: ${SUPABASE_S3_REGION}
    access-key: ${SUPABASE_S3_ACCESS_KEY}
    secret-key: ${SUPABASE_S3_SECRET_KEY}
    bucket: ${SUPABASE_S3_BUCKET}

logging:
  level:
    com.lms: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.boot.sql.init: DEBUG
    org.springframework.boot.autoconfigure: DEBUG